version: '3'
services:
  seasar2_sample_app:
    image: tomcat:9-jdk11-corretto
    depends_on:
      - "db"
    ports:
      - 8080:8080
    volumes:
      - ./app/build/libs/:/usr/local/tomcat/webapps/
    links:
      - db
      - db:database
  db:
    image: mysql:5.6
    # コンテナ名を明示的に指定する
    container_name: mysql56
    # ホスト名を明示的に指定する
    hostname: mydb
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/conf:/etc/mysql/conf.d'
